### ISSUE TITLE
BridJ: LoadLibrary error when loading Clp.dll : A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by abhijay-kumar** [quantego/clp-java#10]
I am using clp-java for linear optimization, but when i try to run the code, i get the following error: The process keeps running and the following keeps getting printed repeatedly.

BridJ: LoadLibrary error when loading C:\Users\Abhijay\AppData\Local\Temp\CLPExtractedLib1623275631902676\Clp.dll : A dynamic link library (DLL) initialization routine failed.

I have added the following dependencies in the pom.xml.

<dependency>
    <groupId>com.quantego</groupId>
    <artifactId>clp-java</artifactId>
    <version>1.16.10</version>
</dependency>

Here is my code:

import com.quantego.clp.CLP;
import com.quantego.clp.CLP.ALGORITHM;
import com.quantego.clp.CLPVariable;

public class ClpDemo {

    public static void main(String[] args) {
        CLP model = new CLP().algorithm(ALGORITHM.AUTO).maximization().presolve(false);
        CLPVariable x1 = model.addVariable().lb(0);
        CLPVariable x2 = model.addVariable().lb(0);
        model.createExpression().add(10, x1).add(20, x2).leq(120);
        model.createExpression().add(8, x1).add(8, x2).leq(80);
        model.createExpression().add(12, x1).add(16, x2).asObjective();
        model.solve();
        double x1Value = model.getSolution(x1);
        double x2Value = model.getSolution(x2);
        System.out.println("x1 :" + x1Value + " x2 :" + x2Value);
      }
}

**Comment by quangdung** [comment]
Maybe this could help: https://github.com/quantego/clp-java/issues/2

`sudo apt-get install coinor-clp`

**Comment by loehndorf** [comment]
Try the latest release: https://github.com/quantego/clp-java/releases
This should be fixed by now. The whole idea of having built it in this way is to avoid installing a CLP binary on the system. Otherwise, you can pull the latest version from the dev branch.

**Comment by abhijay-kumar** [comment]
Thanks a lot. The latest release fixed the problem.
Is this going to be added to maven ?

**Comment by loehndorf** [comment]
Yes, once I merge dev and master, I will push this to Maven.

**Comment by skjaldboeka** [comment]
It's been some time since your last message. It would be helpful you pushed the latest release to Maven

**Comment by loehndorf** [comment]
BridJ has been removed.
