### ISSUE TITLE
Version 1.16.11 cannot be found on maven repository

### ISSUE THREAD

**Issue by avreih** [quantego/clp-java#12]
See also https://stackoverflow.com/questions/58732194/how-to-solve-a-simple-linear-problem-with-clp-java

**Comment by javierseixas** [comment]
+1

**Comment by loehndorf** [comment]
I'll update to 1.16.13 directly but keep this open until this is done.

**Comment by loehndorf** [comment]
https://central.sonatype.com/artifact/com.quantego/clp-java/1.16.10/versions
