### ISSUE TITLE
Change CLP.maxSeconds argument type from int to double

### ISSUE THREAD

**Issue by staffanu** [quantego/clp-java#14]
The underlying C++ code uses a double for the maxSeconds timeout value, but the java wrapper uses an int argument type. My application solves a large number of small problems that should typically take around 50-100 ms, so I want to abort after maybe 300 ms or so for problems that are "too hard".

```
diff --git a/src/main/java/com/quantego/clp/CLP.java b/src/main/java/com/quantego/clp/CLP.java
index da14195..8f78ed1 100644
--- a/src/main/java/com/quantego/clp/CLP.java
+++ b/src/main/java/com/quantego/clp/CLP.java
@@ -630,7 +630,7 @@ public class CLP {
         * @param seconds
         * @return builder
         */
-       public CLP maxSeconds(int seconds) {
+       public CLP maxSeconds(double seconds) {
                CLPNative.clpSetMaximumSeconds(_model, seconds);
                return this;
        }
```

Since the change is very small I didn't fork to make a pull request and hope this comment is enough.

Staffan

**Comment by loehndorf** [comment]
Already resolved (cf dev branch)
