### ISSUE TITLE
dlopen error

### ISSUE THREAD

**Issue by ghost** [quantego/clp-java#2]
Hi,
First of all, thanks for creating this library. It looks great :+1: 

I am unfortunately having some issues with it. I have included your .jar from Maven (as you describe) ... btw. please write somewhere that Java 1.8 is expected.

If I execute the Java statement: `new CLP();`, I get the following output:

`kasper@KasperVB:~/workspace/CPCSolver/target$ java -jar cpc-solver-1-jar-with-dependencies.jar 
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
 BridJ: dlopen error when loading /tmp/CLPExtractedLib4449854949675/libClp.so : libCoinUtils.so.3: cannot open shared object file: No such file or directory
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.quantego.clp.CLPNative.clpNewModel()Lorg/bridj/Pointer;
    at com.quantego.clp.CLPNative.clpNewModel(Native Method)
    at com.quantego.clp.CLP.init(CLP.java:73)
    at com.quantego.clp.CLP.<init>(CLP.java:69)
    at com.bi.solve.main(solve.java:16)`

**Comment by loehndorf** [comment]
It seems that the dependency libCoinUtils-3.so cannot be found. Which Linux release/version are you using? I have tested this under a recent Debian, where it works just fine.

**Comment by ghost** [comment]
I am using ubuntu 14.04 LTS. When I check the tmp folder, I can see that no file was created.

**Comment by loehndorf** [comment]
As designed. It cleans up automatically afterwards. I will fix this. Hang in there.

**Comment by loehndorf** [comment]
I think I have this fixed. At least I dont get errors in Ubuntu 14.04. I have updated maven central as well. Let me know if it works now.

**Comment by ghost** [comment]
I cleared my ~/.m2 and my project target folder and downloaded the dependencies from maven anew. Unfortunately I have exactly the same problem still :|

**Comment by loehndorf** [comment]
This kind of destroys the purpose of a self-contained jar, but try the following: `sudo apt-get install coinor-clp`. This will install the missing dependencies such as lapack and coinutils.

**Comment by ghost** [comment]
it works now.

**Comment by prubin73** [comment]
I ran into the same problem on Mint Rebecca 17.2 (built on Ubuntu 14.04). Installing coinor-clp and two dependencies (coinor-libclp1 and coinor-libosi1) fixed the problem for me.

**Comment by loehndorf** [comment]
The dependencies of the clp lib are copied into the same temp folder as the lib itself, but apparently the clp lib keeps looking for them elsewhere.

**Comment by prubin73** [comment]
It seems unlikely that would be hard-coded behavior in CLP, but if so, perhaps someone on the CLP mailing list would know something about it?

**Comment by Mangara** [comment]
I had this same issue on Ubuntu. Adding the line
`BridJ.addNativeLibraryDependencies("Clp", "CoinUtils");`
before `BridJ.register();` in `CLPNative.java` resolves the issue for me.

I'm not sure how this affects behaviour on other platforms, though.

**Comment by Mangara** [comment]
Testing with the dependency modification on Windows, I now get the following error:
`com.quantego.clp.CLPNative.clpNewModel()Lorg/bridj/Pointer;
java.lang.UnsatisfiedLinkError`
With the log message `INFO: Library not found : CoinUtils`. So a full work-around will involve a little more effort.

**Comment by loehndorf** [comment]
#5

**Comment by quangdung** [comment]
Hello, today I had the same issue on Linux (Ubuntu 16.04). I run `sudo apt-get install coinor-clp` to solve it for now.
