### ISSUE TITLE
How to resolve (warm start) after model modification

### ISSUE THREAD

**Issue by axelvonkamp** [quantego/clp-java#20]
When using solve() then clpInitialSolve() is being called which as far as I understand solves the model from scratch. Clp also has a resolve() method (at least in the 1.17.6 release, https://www.coin-or.org/Doxygen/Clp/classOsiClpSolverInterface.html) but I cannot find this in the CLP class. Would it be possible to make this feature available?

**Comment by loehndorf** [comment]
We are currently using clpDual and clpPrimal, which do this automatically afaik.
