### ISSUE TITLE
Windows 11 - 64-Bit CLP resource is missing in All-in-One-jar

### ISSUE THREAD

**Issue by TheDevSchnitzel** [quantego/clp-java#21]
Hi there,

I recently started working with your CLP interface and noticed on windows there is a problem regarding 32-/64-Bit implementation.

On a 64-Bit Windows 11 the classloader correctly assumes to load a 64-Bit CLP version:
<img width="749" alt="CLP_NativeLoader" src="https://github.com/quantego/clp-java/assets/32178182/a77e8d07-2227-4fee-a36e-192ef1a76e17">

Still, there is none in the [All-in-One-jar](https://github.com/quantego/clp-java?tab=readme-ov-file#all-in-one-jar-file) file provided:
<img width="391" alt="CLP_Res_win-x86" src="https://github.com/quantego/clp-java/assets/32178182/9a853fdf-8b8f-4148-a91c-852fa9f02af5">

A workaround (not optimal though) currently is to rename the resource folder in the .jar file manually:
<img width="385" alt="CLP_Res_win64" src="https://github.com/quantego/clp-java/assets/32178182/6c4d8e91-7d68-4c04-b798-e4b8a2fb5b2b">

Just leaving this here :)
Thanks for the work put into the interface!

**Comment by loehndorf** [comment]
I now fixed the path issues and tested this inside a VM where it works. Please give this a go.

**Comment by loehndorf** [comment]
I consider this issue closed as I was able to verify on a 64-bit intel windows machine.
