### ISSUE TITLE
CLP Boolean Variable?

### ISSUE THREAD

**Issue by weyanteric** [quantego/clp-java#3]
Hi,

Thanks for your work on this project. 

I was wondering if there is any way to create a boolean CLPVariable, as in the variable will only be able to take the values of 0 or 1. Currently having issues with variables taking decimal values when setting the bounds to (0,1). 

Thanks again!

**Comment by loehndorf** [comment]
CLP is a linear programming solver. To have boolean variables, we would have to switch to CBC: http://www.coin-or.org/projects/Cbc.xml

Feel free to fork my project if you want to adapt clp-java to CBC. I think that a lot of the objects and functions could be reused. Most time will probably go into their C interface having different/more functions and enums.
