### ISSUE TITLE
Support for Quadratic objective functions

### ISSUE THREAD

**Issue by Mangara** [quantego/clp-java#4]
It seems that CLP can handle (linearly constrained) quadratic programming, so it would be nice to be able to use this functionality from clp-java.

**Comment by loehndorf** [comment]
I agree. This would be a nice feature.

The objective function of a quadratic program in standard form is 1/2*x'Qx+c'x. The function `CLPNative.clpLoadQuadraticObjective` accepts the matrix Q - at least this is what I believe will happen when calling it, as it is described [here](http://www.coin-or.org/Doxygen/Clp/classClpModel.html#a2e46541a398847f7c9dd02fede88e378). Not sure if I have to multiply with 1/2 or if the solver does this.

Nevertheless, it means that we must buffer the entire matrix internally and pass it through this function before calling the solver.

**Comment by loehndorf** [comment]
I have added QP functionality. See https://github.com/quantego/clp-java/commit/5a8a5c963f1e3e2873ff918e84b825c548db0908 on develop branch. Currently, it only supports diagonal Q matrix (the docs of the clp c interface are simply not exhaustive enough for me to understand how to pass a more general Q). I recommend you give it a try.

**Comment by pet-mit** [comment]
Hello Nils
Thank you for this great work!
Any chance you're pushing the QP functionality to release branch and Maven soon ?

**Comment by loehndorf** [comment]
Hi, I am not 100% happy with this feature yet, as it still only support diagonal QP. I will push the feature, once I have full QP figured out.

**Comment by pet-mit** [comment]
Got it, thanks for the quick response!

**Comment by bgacias83** [comment]
Hello @loehndorf , thank you for doing this work. i think i have a version for the quadratic objective accepting also cross terms. I can share the code if it is ok for you.

**Comment by loehndorf** [comment]
@bgacias83 I would very much interested. Will you be able to put up a pull request? I wonder whether you also created a QuadraticExpression for this.

**Comment by loehndorf** [comment]
I'll close this issue, because my own tests concluded that the QP solver inside CLP is not very stable.
