### ISSUE TITLE
Full (simple) example

### ISSUE THREAD

**Issue by Jacksay** [quantego/clp-java#6]
Hi,
Can you add an very simple (copy/paste) functionnal example to the README please (like this one http://lpsolve.sourceforge.net/5.5/Java/README.html#usage).
Thanks

**Comment by loehndorf** [comment]
Have you checked out the [unit tests](https://github.com/quantego/clp-java/blob/release/src/test/java/com/quantego/clp/CLPTest.java)? Does this qualify as a full simple example?

**Comment by Jacksay** [comment]
No... I will do it. Thanks
