### ISSUE TITLE
MIP support (CBC?)

### ISSUE THREAD

**Issue by jgFages** [quantego/clp-java#7]
Hi,

First thank you very much, clp-java works very well. 
It is a pleasure to simply import the jar file and have nothing else to install. 
Would you consider doing the same for CBC, which enables to have integer variables?
Thank you!

**Comment by loehndorf** [comment]
Thanks! I am planning on doing this for CBC, but I will have to start from scratch. I will do this as soon as I need an integer solver myself. So no promises on the time line, but it's definitely on the stack.

**Comment by jgFages** [comment]
Excellent! Thank you again.
Ok so I understand it would be a different project, I close the issue
