### ISSUE TITLE
Supporting ClpModel::writeMps

### ISSUE THREAD

**Issue by tomwhoiscontrary** [quantego/clp-java#8]
I would find it really useful to be able to export an MPS file of my model. This is supported by Clp itself, but not exposed by clp-java.

In particular, i notice that although CLPNative has a binding for [ClpModel::readMps](https://github.com/quantego/clp-java/blob/release/src/main/java/com/quantego/clp/CLPNative.java#L86), it lacks one for ClpModel::writeMps. I also notice that the [header](https://github.com/quantego/clp-java/blob/release/src/main/java/com/quantego/clp/CLPNative.java#L9) in this file suggests it was generated for Clp 1.13.9, when the library uses Clp 1.16.10. I hazard a guess that the wroteMps method was added in between 1.13 and 1.16.

If CLPNative had a binding for writeMps, it looks to me like it would be pretty simple to wrap it in the same way that CLP::storeModel wraps CLPNative:::clpSaveModel.

As a workaround, i've tried using CLP::storeModel, then importing it into the clp command-line tool to re-export as MPS. However, the command-line tool chokes on the file, saying "There were errors on input".

**Comment by loehndorf** [comment]
You're right. The JNArator said it used 1.13.9, although the lib is clearly 1.16.10. You can sure just give it a try and add the header to see if it works. The function storeModel is better in some cases because it also stores the state of the solver, which is important to reproduce bugs.

I will look into the issue of version mismatch. There might be other functions that could be handy as well.

**Comment by tomwhoiscontrary** [comment]
I think i was wrong. CLPNative wraps the C API, not the C++ API. The C API does not contain writeMps.

It's not clear to me that we could support writing MPS files without either changing the C API itself, or binding to a whole new API, in C++. I'm not sure either of those things are worth the benefit.

**Comment by loehndorf** [comment]
Glad to hear. I looked at this yesterday, but could not find anything either and was going to dig deeper. [JavaCPP](https://github.com/bytedeco/javacpp) provides an alternative to embed C++-apis. May be worth looking into if one was going to entirely revise the interface. It should also be possible to add that function to the C interface, unless there is a reason why this would not work.
